import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { freshEnv, writeGlobalConfig, writeRepoConfig, laneRun, stripLogTimestamps } from './helpers.js';
import { enqueue, tryStart } from '../src/scheduler.js';
import { writeLease } from '../src/lease.js';
import { paths, atomicWriteJson, bootId } from '../src/state.js';
import { readLastSimDemandAt, touchSimArm } from '../src/sim-arm.js';
import { evaluateQueue } from '../src/allocation.js';
import { captureShadowInputs, existingGuardsFor } from '../src/allocation-shadow.js';
import { collectStatus, renderStatusText } from '../src/status.js';

/**
 * BRAIN-379 slice 2: the shadow wiring. Real tryStart against a temp state dir with the CPU sampler
 * and memory reader injected. Fixture machine: 10 cores, reserve 1, 100% -> B = 9.
 */

import { fileURLToPath } from 'node:url';
import { loadModules, baseCfg as scenarioBaseCfg, heldLease as scenarioHeldLease, sampler, memory, ticket, sim, scenarios, runScript, liveTrace } from './allocation-scenarios.js';

const GIB = 1024 ** 3;
const SHADOW_TOKEN = 'lane-broker-allocation-shadow';
const m = await loadModules(fileURLToPath(new URL('../src', import.meta.url)));
const baseCfg = (overrides) => scenarioBaseCfg(m, overrides);
const heldLease = (...args) => scenarioHeldLease(m, ...args);

const poll = (state, t, cfg, { ext = 0, evaluator, capture, mem = memory } = {}) => tryStart(state, t, cfg, undefined, sampler(ext), undefined, mem, undefined, { evaluator, capture });

const readLog = (state) => {
  try {
    return stripLogTimestamps(fs.readFileSync(paths(state).admissionLog, 'utf8'));
  } catch {
    return '';
  }
};
const shadowLines = (state) => readLog(state).split('\n').filter((l) => l.startsWith(`${SHADOW_TOKEN} `));
// the decision-relevant config values every record carries (the fixture machine's, see baseCfg)
const CFG_EVIDENCE = 'lockT:0.15,lockS:0.3,armWindowMs:300000,mode:active,capacity:10,cpuPct:100,cpuReserve:1,memReserveB:2147483648,memCloseB:4294967296,memOpenB:8589934592,conflictSkip:3,resourceSkip:3,loadGate:false,safeBackfill:true';
const liveLines = (state) => readLog(state).split('\n').filter((l) => l && !l.startsWith(SHADOW_TOKEN));
const field = (line, name) => new RegExp(`(?:^| )${name}=(\\S*)`).exec(line)?.[1];
const candidateOf = (line, idPrefix) => field(line, 'candidates').split(',').find((c) => c.startsWith(`${idPrefix}:`));

// ---- the hard invariant -------------------------------------------------------------------------

// What proves each script really drove its skip machinery (the head's start clears the resource record, so that one shows in the live log).
const EXERCISED = {
  resource: (r) => r.liveLog.some((l) => /event=resource-backfill-start/.test(l)),
  conflict: (r) => r.conflictSkip !== null,
  capacity: (r) => r.capacitySkip !== null,
};
const SCENARIOS = scenarios(m);

for (const name of Object.keys(SCENARIOS)) {
  test(`live selection is byte-identical with shadow on and off (${name}): admission sequence, skip/reservation files, leases, queue, live log`, async () => {
    const off = await runScript(m, SCENARIOS[name], { allocationShadow: false });
    const on = await runScript(m, SCENARIOS[name], { allocationShadow: true });
    assert.deepEqual(on.results, off.results, 'identical admission sequence');
    for (const file of ['conflictSkip', 'capacitySkip', 'resourceSkip']) assert.equal(on[file], off[file], `${file} state file is byte-identical`);
    assert.deepEqual(on.leases, off.leases, 'identical lease files');
    assert.deepEqual(on.queue, off.queue, 'identical queue files');
    assert.deepEqual(on.liveLog, off.liveLog, 'identical live admission log lines');
    assert.equal(off.shadowLines.length, 0, 'shadow off writes no shadow record');
    assert.ok(on.shadowLines.length >= 2, `shadow on records evaluations (got ${on.shadowLines.length})`);
    assert.ok(EXERCISED[name](off), `the script really exercised the ${name} skip path (otherwise this proves nothing)`);
    assert.ok(off.results.some((r) => r.started) && off.results.some((r) => !r.started), 'script mixes starts and denials');
  });
}

// The traces were generated by running these same scripts on MAIN's code (see allocation-scenarios.js), so this
// is the comparison against the pre-change broker that the on/off test above cannot make.
const GOLDEN = JSON.parse(fs.readFileSync(new URL('./fixtures/allocation-golden-trace.json', import.meta.url), 'utf8'));
for (const name of Object.keys(SCENARIOS)) {
  test(`GOLDEN TRACE (${name}): the branch with shadow ON reproduces main's admission trace exactly`, async () => {
    const on = await runScript(m, SCENARIOS[name], { allocationShadow: true });
    assert.deepEqual(liveTrace(on), GOLDEN[name]);
    assert.ok(on.shadowLines.length >= 2, 'shadow really ran');
  });
}

test('the shadow path never writes a skip counter or a reservation record, even when it would consume skip budget', async () => {
  // Live: the test head starts (CPU fits). Shadow: sims are armed by the queued sim, the head's claim
  // breaches the sim lock, so the hypothetical selection is a BACKFILL that consumes one skip.
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  writeLease(state, heldLease('held', 'r:held', 5, { resources: { cpuCores: 5, memoryBytes: GIB } }));
  await enqueue(state, ticket('head', { weight: 3 }));
  await enqueue(state, sim('s1'));
  const result = await poll(state, ticket('head', { weight: 3 }), cfg, { ext: 0 });
  assert.equal(result.started, true, 'live admits the head');
  const [line] = shadowLines(state);
  assert.equal(field(line, 'select'), 's1', 'shadow would have picked the sim instead');
  assert.equal(field(line, 'selectReason'), 'backfill');
  assert.match(line, / skip=none:0\+1\/3 /, 'hypothetical consumption is reported');
  const p = paths(state);
  for (const file of [p.conflictSkipState, p.capacitySkipState, p.resourceSkipState]) assert.equal(fs.existsSync(file), false, `${path.basename(file)} must not exist`);
});

test('a throw inside the shadow evaluation is logged as a shadow error and leaves the live decision intact', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  await enqueue(state, ticket('head'));
  const result = await poll(state, ticket('head'), cfg, {
    evaluator: () => {
      throw new Error('injected shadow failure');
    },
  });
  assert.equal(result.started, true, 'live decision unaffected');
  assert.ok(fs.existsSync(path.join(paths(state).leases, 'head.json')), 'lease was written');
  assert.equal(shadowLines(state).length, 0, 'no shadow record');
  assert.match(readLog(state), /lane-broker-allocation-shadow-error poller=head error=injected_shadow_failure/);
  assert.equal(liveLines(state).filter((l) => l.startsWith('lane-broker-admission ')).length, 1, 'the live admission line is still written');
});

// ---- the record --------------------------------------------------------------------------------

test('a shadow record is written for a blocked head evaluation, carrying the actual live outcome', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  await enqueue(state, ticket('head', { weight: 4 }));
  const denied = await poll(state, ticket('head', { weight: 4 }), cfg, { ext: 5.4 });
  assert.equal(denied.reason, 'cpu-admission');
  const [line] = shadowLines(state);
  assert.equal(field(line, 'poller'), 'head');
  assert.equal(field(line, 'actual'), 'cpu-admission');
  assert.equal(field(line, 'budgetSource'), 'live');
  assert.equal(field(line, 'B'), '9');
  assert.equal(field(line, 'externalBusy'), '5.4');
});

test('5 queued tickets polling through one cycle with no start write exactly 1 shadow line (the head\'s)', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  const ids = ['q1', 'q2', 'q3', 'q4', 'q5'];
  for (const id of ids) await enqueue(state, ticket(id, { weight: 4 }));
  for (const id of ids) {
    const r = await poll(state, ticket(id, { weight: 4 }), cfg, { ext: 8 });
    assert.equal(r.started, false);
  }
  const lines = shadowLines(state);
  assert.equal(lines.length, 1);
  assert.equal(field(lines[0], 'poller'), 'q1');
});

test('a non-head backfill start writes a shadow record with actual=started', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  await enqueue(state, ticket('head', { weight: 4 }));
  await enqueue(state, ticket('small'));
  await poll(state, ticket('head', { weight: 4 }), cfg, { ext: 5.4 });
  const started = await poll(state, ticket('small'), cfg, { ext: 5.4 });
  assert.equal(started.started, true);
  const lines = shadowLines(state);
  assert.equal(lines.length, 2);
  assert.equal(field(lines[1], 'poller'), 'small');
  assert.equal(field(lines[1], 'head'), 'head');
  assert.equal(field(lines[1], 'actual'), 'started');
});

test('the shadow record format: B, usage, locks, arm state, selection, actual outcome, per-candidate verdicts', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  writeLease(state, heldLease('held', 'r:held', 5, { class: 'test', resources: { cpuCores: 5, memoryBytes: GIB } }));
  await enqueue(state, ticket('headaaaa-1111', { weight: 3 }));
  await enqueue(state, sim('simbbbbb-2222'));
  await poll(state, ticket('headaaaa-1111', { weight: 3 }), cfg);
  const [line] = shadowLines(state);
  const stamp = readLastSimDemandAt(state);
  assert.ok(Number.isFinite(stamp));
  assert.equal(
    line,
    `${SHADOW_TOKEN} ts=${field(line, 'ts')} poller=headaaaa head=headaaaa actual=started select=simbbbbb selectReason=backfill B=9 budgetSource=live chargeSource=live externalBusy=0 ` +
      `used_t=5 used_s=0 L_t=1.35 L_s=2.7 armed=true lastSimDemandAt=${stamp} cfg=${CFG_EVIDENCE} skip=none:0+1/3 reserved=false ` +
      'candidates=headaaaa:test:c=3:e=3:k=3:class-lock,simbbbbb:sim:c=1:e=1:k=1:ok',
  );
});

// ---- the arm stamp -----------------------------------------------------------------------------

test('the arm stamp is written on a sim enqueue, not on a test enqueue', async () => {
  const { state } = freshEnv();
  await enqueue(state, ticket('t1'));
  assert.equal(readLastSimDemandAt(state), null);
  assert.equal(fs.existsSync(paths(state).simArm), false);
  const before = Date.now();
  await enqueue(state, sim('s1'));
  assert.ok(readLastSimDemandAt(state) >= before);
});

test('the arm stamp is reconciled from queue and lease state at a locked evaluation', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg();
  await enqueue(state, ticket('head'));
  await enqueue(state, sim('s1'));
  fs.unlinkSync(paths(state).simArm);
  await poll(state, ticket('head'), cfg);
  assert.ok(readLastSimDemandAt(state) !== null, 'a queued sim re-stamps a lost file');

  // a charged sim lease alone (empty queue of sims) also re-stamps
  const second = freshEnv();
  writeLease(second.state, heldLease('simrun', 'r:simrun', 1, { class: 'sim' }));
  await enqueue(second.state, ticket('t'));
  await poll(second.state, ticket('t'), cfg);
  assert.ok(readLastSimDemandAt(second.state) !== null, 'a charged sim lease stamps');

  // no sim anywhere: nothing is written
  const third = freshEnv();
  await enqueue(third.state, ticket('t'));
  await poll(third.state, ticket('t'), cfg);
  assert.equal(fs.existsSync(paths(third.state).simArm), false);
});

test('a corrupt or missing arm file means unarmed with no history, never a crash', async () => {
  for (const content of [null, '{not json', '"a string"', '{"lastSimDemandAt":"soon"}', 'null']) {
    const { state } = freshEnv();
    if (content !== null) fs.writeFileSync(paths(state).simArm, content);
    assert.equal(readLastSimDemandAt(state), null);
    const cfg = baseCfg({ allocationShadow: true });
    writeLease(state, heldLease('held', 'r:held', 5, { resources: { cpuCores: 5, memoryBytes: GIB } }));
    await enqueue(state, ticket('head', { weight: 2 }));
    const result = await poll(state, ticket('head', { weight: 2 }), cfg);
    assert.equal(result.started, true);
    const [line] = shadowLines(state);
    assert.equal(field(line, 'armed'), 'false', `content ${JSON.stringify(content)}`);
    assert.equal(field(line, 'lastSimDemandAt'), 'none');
    assert.equal(field(line, 'L_s'), '0');
  }
});

test('a recent arm stamp arms the sim lock with no sim queued or running, and an old one does not', async () => {
  for (const [ageMs, armed] of [[60_000, 'true'], [10 * 60_000, 'false']]) {
    const { state } = freshEnv();
    const cfg = baseCfg({ allocationShadow: true });
    atomicWriteJson(paths(state).simArm, { lastSimDemandAt: Date.now() - ageMs });
    await enqueue(state, ticket('head'));
    await poll(state, ticket('head'), cfg);
    assert.equal(field(shadowLines(state)[0], 'armed'), armed, `stamp ${ageMs}ms old`);
  }
});

test('the arm stamp is touched on admission of a sim, and the lease carries its class', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg();
  await enqueue(state, sim('s1'));
  fs.unlinkSync(paths(state).simArm);
  const result = await poll(state, sim('s1'), cfg);
  assert.equal(result.started, true);
  assert.equal(result.lease.class, 'sim', 'the lease record carries the class');
  assert.ok(readLastSimDemandAt(state) !== null);
  assert.equal(JSON.parse(fs.readFileSync(path.join(paths(state).leases, 's1.json'), 'utf8')).class, 'sim');
});

test('the arm stamp is touched on a queued sim cancel and on a reaped sim lease', async () => {
  const { state } = freshEnv();
  const prev = process.env.LANE_BROKER_STATE;
  process.env.LANE_BROKER_STATE = state;
  try {
    await enqueue(state, sim('s1'));
    fs.unlinkSync(paths(state).simArm);
    const { cancelCommand } = await import('../src/cancel.js');
    assert.equal((await cancelCommand('s1')).exitCode, 0);
    assert.ok(readLastSimDemandAt(state) !== null, 'queued cancel stamps');

    fs.unlinkSync(paths(state).simArm);
    writeLease(state, heldLease('dead', 'r:dead', 1, { class: 'sim', supervisorPid: 2 ** 22 + 12345, childPgid: 2 ** 22 + 54321 }));
    const { reapAll } = await import('../src/lease.js');
    assert.deepEqual(reapAll(state, bootId()), [{ id: 'dead', action: 'reaped' }]);
    assert.ok(readLastSimDemandAt(state) !== null, 'orphan reap stamps');
  } finally {
    if (prev === undefined) delete process.env.LANE_BROKER_STATE;
    else process.env.LANE_BROKER_STATE = prev;
  }
});

// ---- status ------------------------------------------------------------------------------------

test('lane status shows the allocation line and object only when allocationShadow is on', async () => {
  const { state, home } = freshEnv();
  const prevState = process.env.LANE_BROKER_STATE;
  const prevHome = process.env.LANE_BROKER_HOME;
  process.env.LANE_BROKER_STATE = state;
  process.env.LANE_BROKER_HOME = home;
  try {
    writeLease(state, heldLease('held', 'r:held', 2, { class: 'test', resources: { cpuCores: 2, memoryBytes: GIB } }));
    await enqueue(state, sim('s1', 1));
    const off = await collectStatus();
    assert.equal('allocation' in off, false);
    assert.doesNotMatch(renderStatusText(off), /allocation \(shadow\)/);

    fs.writeFileSync(path.join(home, 'config.json'), JSON.stringify({ version: 1, allocationShadow: true, schedulerMode: 'shadow' }));
    const on = await collectStatus();
    assert.equal(on.allocation.shadow, true);
    assert.equal(on.allocation.armed, true, 'a queued sim arms');
    assert.equal(on.allocation.test.used, 2);
    assert.equal(on.allocation.sim.queued, 1);
    assert.ok(on.allocation.sim.target > 0);
    const text = renderStatusText(on);
    assert.match(text, /^allocation \(shadow\): test used 2\.00\/target [\d.]+ queued 0\.00; sim used 0\.00\/target [\d.]+ queued 1\.00; sims armed$/m);
  } finally {
    if (prevState === undefined) delete process.env.LANE_BROKER_STATE;
    else process.env.LANE_BROKER_STATE = prevState;
    if (prevHome === undefined) delete process.env.LANE_BROKER_HOME;
    else process.env.LANE_BROKER_HOME = prevHome;
  }
});

// ---- review round: lock discipline, guard parity, skip budget, charges, arm-stamp exits -------------

test('the shadow evaluation and its log append run AFTER the global lock is released', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  await enqueue(state, ticket('head'));
  let lockHeldDuringEvaluation = null;
  let lockHeldAtLogAppend = null;
  const result = await poll(state, ticket('head'), cfg, {
    evaluator: (args) => {
      lockHeldDuringEvaluation = fs.existsSync(paths(state).lock);
      const evaluation = evaluateQueue(args);
      lockHeldAtLogAppend = fs.existsSync(paths(state).lock); // the append follows immediately in the same tick
      return evaluation;
    },
  });
  assert.equal(result.started, true);
  assert.equal(lockHeldDuringEvaluation, false, 'evaluator ran with the lock still held');
  assert.equal(lockHeldAtLogAppend, false);
  assert.equal(shadowLines(state).length, 1);
});

test('the hypothetical admission includes the existing guards: weight capacity, memory brake, pause, cooldown', async () => {
  const headAt = async (setup, cfgOverrides, pollOptions) => {
    const { state } = freshEnv();
    const cfg = baseCfg({ allocationShadow: true, ...cfgOverrides });
    setup?.(state);
    await enqueue(state, ticket('head', { weight: 3 }));
    const live = await poll(state, ticket('head', { weight: 3 }), cfg, pollOptions);
    const line = shadowLines(state)[0];
    return { live, line, head: candidateOf(line, 'head') };
  };

  // BRAIN-452: a weight-3 head is allowed at capacity 6, so capacity is exhausted by a held weight-4 lease instead
  const capacity = await headAt((state) => writeLease(state, heldLease('held', 'r:held', 4, { resources: { cpuCores: 1, memoryBytes: GIB } })), { capacity: 6 });
  assert.equal(capacity.live.reason, 'capacity');
  assert.match(capacity.head, /:capacity:guards=capacity$/);
  assert.equal(field(capacity.line, 'select'), 'none', 'a weight-3 candidate is not selectable beside a weight-4 lease at capacity 6');

  const memoryCritical = await headAt(null, {}, { mem: () => ({ availableBytes: GIB, totalBytes: 64 * GIB, macPressure: 'critical', source: 'test' }) });
  assert.equal(memoryCritical.live.reason, 'memory-critical');
  assert.match(memoryCritical.head, /:memory-critical:guards=memory-critical(\||$)/);
  assert.equal(field(memoryCritical.line, 'select'), 'none');

  const paused = await headAt((state) => fs.writeFileSync(paths(state).pause, 'maintenance'), {});
  assert.equal(paused.live.reason, 'paused');
  assert.match(paused.head, /:paused:guards=paused\|unknown$/, 'no CPU/memory sample was taken, so those guards are unknown');

  const cooldown = await headAt(
    (state) => writeLease(state, heldLease('held', 'r:held', 1, { resources: { cpuCores: 1, memoryBytes: GIB } })),
    { admissionCooldownMs: 600_000 },
  );
  assert.equal(cooldown.live.cpuReason, 'cooldown');
  assert.match(cooldown.head, /:cooldown:guards=cooldown$/);
  assert.equal(field(cooldown.line, 'select'), 'none');

  const clear = await headAt(null, {});
  assert.equal(clear.live.started, true);
  assert.match(clear.head, /:ok$/, 'with every guard passing the same candidate is ok');
  assert.equal(field(clear.line, 'select'), 'head');
});

test('class-only skips spend the resource skip budget, not the conflict one (unequal limits)', async () => {
  const run = async (cfgOverrides) => {
    const { state } = freshEnv();
    const cfg = baseCfg({ allocationShadow: true, ...cfgOverrides });
    writeLease(state, heldLease('held', 'r:held', 5, { resources: { cpuCores: 5, memoryBytes: GIB } }));
    await enqueue(state, ticket('head', { weight: 3 }));
    await enqueue(state, sim('s1'));
    const live = await poll(state, ticket('head', { weight: 3 }), cfg);
    assert.equal(live.started, true, 'live is unaffected either way');
    return shadowLines(state)[0];
  };
  const open = await run({ conflictSkipLimit: 7, resourceSkipLimit: 1 });
  assert.match(open, / skip=none:0\+1\/1 /, 'limit is resourceSkipLimit (1), not conflictSkipLimit (7)');
  assert.equal(field(open, 'selectReason'), 'backfill');
  const exhausted = await run({ conflictSkipLimit: 7, resourceSkipLimit: 0 });
  assert.match(exhausted, / skip=none:0\+0\/0 /);
  assert.equal(field(exhausted, 'selectReason'), 'skip-budget-exhausted');
  assert.equal(field(exhausted, 'select'), 'none');
});

test('the record carries the evaluation timestamp, config values, per-candidate claims and reservation amounts', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true, simArmWindowMs: 120_000 });
  await enqueue(state, ticket('head', { weight: 3 }));
  await enqueue(state, ticket('big', { weight: 5, resources: { cpuCores: 8, memoryBytes: GIB } })); // BRAIN-452: weight capped at 5; the 8-core claim stays
  await poll(state, ticket('head', { weight: 3 }), cfg);
  const [line] = shadowLines(state);
  assert.ok(Number.isFinite(Number(field(line, 'ts'))));
  assert.equal(field(line, 'cfg'), CFG_EVIDENCE.replace('armWindowMs:300000', 'armWindowMs:120000'));
  assert.match(candidateOf(line, 'head'), /^head:test:c=3:e=3:k=3:ok$/);
  assert.equal(candidateOf(line, 'big'), 'big:test:c=8:e=6:k=6:ok', 'an oversized test claim (8 > B - L_s = 6.3) is clamped to floor(6.3)');
  assert.equal(field(line, 'chargeSource'), 'recomputed', 'nothing held, so there were no live charges to reuse');
});

test('a held lease is charged at the demand the live CPU evaluation computed (chargeSource=live)', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  writeLease(state, heldLease('held', 'r:held', 4, { resources: { cpuCores: 4, memoryBytes: GIB } }));
  await enqueue(state, ticket('head'));
  await poll(state, ticket('head'), cfg);
  const [line] = shadowLines(state);
  assert.equal(field(line, 'chargeSource'), 'live');
  assert.equal(field(line, 'used_t'), '4');
});

test('reconciliation rewrites the arm stamp only when it is stale (older than a tenth of the window), not on every poll', async () => {
  const stampAfterPoll = async (ageMs) => {
    const { state } = freshEnv();
    const cfg = baseCfg();
    await enqueue(state, sim('s1'));
    const seeded = Date.now() - ageMs;
    fs.writeFileSync(paths(state).simArm, JSON.stringify({ lastSimDemandAt: seeded }));
    await poll(state, ticket('nobody'), cfg); // not queued: returns before reconciliation
    await enqueue(state, ticket('head'));
    await poll(state, ticket('head'), cfg);
    return { seeded, after: readLastSimDemandAt(state) };
  };
  const fresh = await stampAfterPoll(1000);
  assert.equal(fresh.after, fresh.seeded, 'a fresh stamp is left alone');
  const stale = await stampAfterPoll(120_000);
  assert.ok(stale.after > stale.seeded, 'a stale stamp is advanced');
});

test('touchSimArm is monotonic: the final value is the max whatever the interleaving', () => {
  const stamp = (state) => readLastSimDemandAt(state);
  const seed = (state, value) => atomicWriteJson(paths(state).simArm, { lastSimDemandAt: value });

  // never moves back
  const plain = freshEnv().state;
  seed(plain, 300);
  assert.equal(touchSimArm(plain, 200), true);
  assert.equal(stamp(plain), 300);

  // the old failure: A is about to write 100, but B completes a write of 200 first. A must re-read under the lock.
  const raced = freshEnv().state;
  seed(raced, 50);
  touchSimArm(raced, 100, { beforeLock: () => touchSimArm(raced, 200) });
  assert.equal(stamp(raced), 200, 'the older writer saw the newer value and left it');

  // and the other order: the older write lands first, the newer one wins
  const forward = freshEnv().state;
  seed(forward, 50);
  touchSimArm(forward, 200, { beforeLock: () => touchSimArm(forward, 100) });
  assert.equal(stamp(forward), 200);

  // mutual exclusion: a writer that arrives while another holds the lock does not interleave a write
  const held = freshEnv().state;
  seed(held, 50);
  let inner;
  touchSimArm(held, 100, { afterRead: () => (inner = touchSimArm(held, 999, { lockWaitMs: 10 })) });
  assert.equal(inner, false, 'the second writer could not take the lock mid read-compare-write');
  assert.equal(stamp(held), 100, 'and so could not interleave its own write');
  assert.equal(fs.existsSync(paths(held).simArmLock), false, 'the lock is released');
});

test('a stale stamp lock left by a crashed writer is broken; a fresh one is respected', () => {
  const { state } = freshEnv();
  const lock = paths(state).simArmLock;
  fs.writeFileSync(lock, '');
  assert.equal(touchSimArm(state, 100, { lockWaitMs: 10 }), false, 'a fresh lock held by someone else is not stolen');
  assert.equal(readLastSimDemandAt(state), null);
  const old = new Date(Date.now() - 60_000);
  fs.utimesSync(lock, old, old);
  assert.equal(touchSimArm(state, 100, { lockWaitMs: 10 }), true);
  assert.equal(readLastSimDemandAt(state), 100);
});

test('with allocationShadow off the shadow snapshot is never built; with it on, once per head poll', async () => {
  const run = async (allocationShadow) => {
    const { state } = freshEnv();
    let builds = 0;
    const capture = (args) => {
      builds += 1;
      return captureShadowInputs(args);
    };
    await enqueue(state, ticket('head'));
    await poll(state, ticket('head'), baseCfg({ allocationShadow }), { capture });
    return { builds, lines: shadowLines(state).length };
  };
  assert.deepEqual(await run(false), { builds: 0, lines: 0 });
  assert.deepEqual(await run(true), { builds: 1, lines: 1 });
});

test('with live admission returning before it sampled, the CPU/load/memory guards are unknown and nothing is hypothetically selected', async () => {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  writeLease(state, heldLease('holder', 'r:lock', 1, { resources: { cpuCores: 1, memoryBytes: GIB } }));
  await enqueue(state, ticket('chead', { key: 'r:lock' }));
  await enqueue(state, ticket('free1'));
  const live = await poll(state, ticket('chead', { key: 'r:lock' }), cfg);
  assert.equal(live.reason, 'not-head', 'live lets the non-conflicting ticket go ahead; this poll never reaches the CPU/memory sample');
  const [line] = shadowLines(state);
  assert.equal(candidateOf(line, 'chead').split(':')[5], 'conflict');
  assert.match(candidateOf(line, 'free1'), /:unknown:guards=unknown$/);
  assert.equal(field(line, 'select'), 'none');
});

test('memory admission counts the blocked head\'s reservation for a safe backfill (and a conflict pick), as live does', () => {
  // 3 GiB budget; the held lease and the head each book 1 GiB, so a 1.5 GiB candidate breaches only WITH the head reserved
  const cfg = baseCfg({ memoryReserveBytes: 0 });
  const withRes = (memoryBytes) => ({ cpuCores: 1, memoryBytes });
  const queue = [ticket('chead', { resources: withRes(GIB) }), ticket('bf', { resources: withRes(1.5 * GIB) })];
  const inputs = (overrides) => ({ cfg, held: [heldLease('holder', 'r:lock', 1, { resources: withRes(GIB) })], queue, safeBackfill: [false, false], conflictPickId: null, paused: false, runningWeight: 1, weightCapacity: 10, ...overrides });
  const live = { memInfo: { availableBytes: 64 * GIB, totalBytes: 3 * GIB, macPressure: 'normal' }, memAt: Date.now(), cpuReason: 'ok', loadGateBlocking: false };
  const guardsFor = (i) => existingGuardsFor(i, live, new Map(queue.map((t, n) => [t, n])))(queue[1]);
  assert.deepEqual(guardsFor(inputs({})), [], 'with no reservation the candidate fits');
  assert.deepEqual(guardsFor(inputs({ safeBackfill: [false, true] })), ['memory-reservations'], 'safe backfill reserves the head');
  assert.deepEqual(guardsFor(inputs({ conflictPickId: 'bf' })), ['memory-reservations'], 'so does a conflict pick');
});

test('shadow memory admission is evaluated at the captured memory observation time, not a fresh clock read', () => {
  const cfg = baseCfg({ memoryReserveBytes: GIB });
  const observedAt = 1_700_000_000_000;
  const holder = heldLease('holder', 'r:h', 1, { resources: { cpuCores: 1, memoryBytes: GIB }, observedAt, observedMemoryBytes: GIB });
  const queue = [ticket('head', { resources: { cpuCores: 1, memoryBytes: GIB / 2 } })];
  const inputs = { cfg, held: [holder], queue, safeBackfill: [false], conflictPickId: null, paused: false, runningWeight: 1, weightCapacity: 10 };
  const memInfo = { availableBytes: 2 * GIB, totalBytes: 64 * GIB, macPressure: 'normal' };
  const guards = (memAt) => existingGuardsFor(inputs, { memInfo, memAt, cpuReason: 'ok', loadGateBlocking: false }, new Map([[queue[0], 0]]))(queue[0]);
  assert.deepEqual(guards(observedAt + 1000), [], 'the observation was fresh at the time live looked');
  assert.deepEqual(guards(observedAt + 120_000), ['memory-headroom'], 'and would have been stale two minutes on; the captured time decides, Date.now() (years later) does not');
});

/** The 5-minute tail: after the LAST sim demand leaves through `exit`, a test head is still held back by an armed sim lock. */
async function assertTailAfter(exit) {
  const { state } = freshEnv();
  const cfg = baseCfg({ allocationShadow: true });
  const prev = process.env.LANE_BROKER_STATE;
  process.env.LANE_BROKER_STATE = state;
  try {
    const before = Date.now();
    await exit(state);
    assert.ok(readLastSimDemandAt(state) >= before, 'the exit stamped the arm file');
    assert.equal(fs.existsSync(paths(state).queue) ? fs.readdirSync(paths(state).queue).length : 0, 0, 'no sim demand remains');
    await enqueue(state, ticket('head'));
    await poll(state, ticket('head'), cfg);
    const [line] = shadowLines(state);
    assert.equal(field(line, 'armed'), 'true', 'sims stay armed for the window');
    assert.equal(field(line, 'L_s'), '2.7');
  } finally {
    if (prev === undefined) delete process.env.LANE_BROKER_STATE;
    else process.env.LANE_BROKER_STATE = prev;
  }
}

const clearStamp = (state) => fs.rmSync(paths(state).simArm, { force: true });
const DEAD_PID = 2 ** 22 + 12345;
const DEAD_PGID = 2 ** 22 + 54321;

test('5-minute tail after a queued sim is cancelled', async () => {
  await assertTailAfter(async (state) => {
    await enqueue(state, sim('s1'));
    clearStamp(state);
    const { cancelCommand } = await import('../src/cancel.js');
    assert.equal((await cancelCommand('s1')).exitCode, 0);
  });
});

test('5-minute tail after an orphaned sim lease is cancelled', async () => {
  await assertTailAfter(async (state) => {
    writeLease(state, heldLease('orph', 'r:orph', 1, { class: 'sim', state: 'ORPHANED', supervisorPid: DEAD_PID, childPgid: DEAD_PGID, resultPath: path.join(state, 'orph-result.json') }));
    clearStamp(state);
    const { cancelCommand } = await import('../src/cancel.js');
    assert.equal((await cancelCommand('orph')).exitCode, 0);
  });
});

test('5-minute tail after a sim lease is reaped', async () => {
  await assertTailAfter(async (state) => {
    writeLease(state, heldLease('dead', 'r:dead', 1, { class: 'sim', supervisorPid: DEAD_PID, childPgid: DEAD_PGID }));
    clearStamp(state);
    const { reapAll } = await import('../src/lease.js');
    assert.deepEqual(reapAll(state, bootId()), [{ id: 'dead', action: 'reaped' }]);
  });
});

test('5-minute tail after a queued sim whose supervisor died is dequeued', async () => {
  await assertTailAfter(async (state) => {
    await enqueue(state, sim('ghost', 1, { supervisorPid: DEAD_PID }));
    clearStamp(state);
    await poll(state, ticket('other'), baseCfg()); // any locked evaluation reaps the dead queued supervisor
  });
});

test('5-minute tail after a sim lane runs to completion (release path), end to end', async () => {
  const { base, home, state, env } = freshEnv();
  writeGlobalConfig(home, { version: 1, capacity: 2, loadClose: 1000, loadOpen: 900, loadOpenSamples: 1, sampleMs: 100 });
  const repoDir = path.join(base, 'repo');
  writeRepoConfig(repoDir, { version: 1, lanes: { default: { weight: 1 }, sims: { weight: 1, class: 'sim' } } });
  const result = await laneRun(['run', '--repo', 'r', '--lane', 'sims', '--', 'sleep', '1'], { env, cwd: repoDir });
  assert.equal(result.code, 0, result.stderr);
  const rows = fs.readFileSync(paths(state).history, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
  const endedAt = rows.at(-1).endedAt;
  assert.ok(Number.isFinite(endedAt));
  assert.ok(readLastSimDemandAt(state) >= endedAt, 'the stamp is at least as late as the end of the run, not just the admission 1s earlier');
});
